enum ListaProductosActionsTypes {
  SET_LISTA_PRODUCTOS = "SET_LISTA_PRODUCTOS",
  PUSH_PRODUCTO = "PUSH_PRODUCTO",
  MODIFY_PRODUCTO = "MODIFY_PRODUCTO",
  DELETE_PRODUCTO = "DELETE_PRODUCTO",
  CHANGE_PRODUCTO_AMOUNT = "CHANGE_PRODUCTO_AMOUNT",
}
export default ListaProductosActionsTypes;
