enum DescripcionActionsTypes {
  SET_DESCRIPCION = "SET_DESCRIPCION",
  ACTIVATE_DESCRIPCION = "ACTIVATE_DESCRIPCION",
  DEACTIVATE_DESCRIPCION = "DEACTIVATE_DESCRIPCION",
}
export default DescripcionActionsTypes;
