enum Precio_venta_netoActionsTypes {
  SET_PRECIO_VENTA_NETO = "SET_PRECIO_VENTA_NETO",
  ACTIVATE_PRECIO_VENTA_NETO = "ACTIVATE_PRECIO_VENTA_NETO",
  DEACTIVATE_PRECIO_VENTA_NETO = "DEACTIVATE_PRECIO_VENTA_NETO",
}
export default Precio_venta_netoActionsTypes;
