enum Codigo_barrasActionsTypes {
  SET_CODIGO_BARRAS = "SET_CODIGO_BARRAS",
  ACTIVATE_CODIGO_BARRAS = "ACTIVATE_CODIGO_BARRAS",
  DEACTIVATE_CODIGO_BARRAS = "DEACTIVATE_CODIGO_BARRAS",
}
export default Codigo_barrasActionsTypes;
